// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').controller('maintenanceInvitedCtrl', function($scope, $state, $http) {
    var code;
    code = window.location.search.replace(/^\?/, '');
    return $scope.acceptInvite = function() {
      if ($scope.repeatPassword === $scope.newUser.local.password) {
        return $http.post('/invite/accept', {
          code: decodeURIComponent(code),
          user: $scope.newUser
        }, $http.sites["maintenance"].config).then(function(response) {
          if (response.data === 'OK') {
            return $state.go('dashboard');
          }
        }, function(err) {
          return false;
        });
      } else {
        return $scope.error = 'Passwords must match';
      }
    };
  });

}).call(this);
