// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').config(function($stateProvider) {
    return $stateProvider.state('maintenance_invited', {
      url: '/maintenance/invited',
      template: require("./invited.html").default,
      controller: 'maintenanceInvitedCtrl'
    });
  });

}).call(this);
