// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_platform', {
      url: '/agency/',
      template: require("./platform.html").default,
      controller: 'agencyPlatformCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Choose Platform',
        hideMenu: true
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise();
        }
      }
    });
  });

}).call(this);
