// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencyPlatformCtrl', function($scope, $state) {
    var hideMenu;
    return hideMenu = $state.current.data.hideMenu;
  });

}).call(this);
