// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_invited', {
      url: '/maintenance_leads/invite/:code',
      template: require("./invited.html").default,
      controller: 'maintenance_leadsInvitedCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Invited'
      }
    });
  });

}).call(this);
