// Generated by CoffeeScript 2.5.1
(function() {
  angular.module('vs-maintenance-leads').controller('maintenance_leadsLightboxCtrl', function($scope, data, $http, ndxModalInstance) {
    $scope.imgSrc = data[0].URL;
    $scope.imgIndex = data;
    return $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
