// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsAgreedCtrl', function($scope, $filter, $timeout, $http) {
    var updateMonths, updateProperties, updateTargets, y;
    $scope.now = new Date().valueOf();
    $scope.years = [];
    y = new Date().getFullYear() + 1;
    while (y-- > 2017) {
      $scope.years.push(y);
    }
    updateMonths = function() {
      var month, results, testDate;
      $scope.months = [];
      testDate = new Date($scope.startDate['startDate']);
      results = [];
      while (testDate < $scope.endDate['startDate']) {
        month = {
          date: testDate,
          month: $filter('date')(testDate, 'MMMM'),
          properties: [],
          target: {
            type: 'letAgreed',
            value: 0,
            date: testDate
          },
          search: ''
        };
        $scope.months.push(month);
        results.push(testDate = new Date(testDate.getFullYear(), testDate.getMonth() + 1, testDate.getDate()));
      }
      return results;
    };
    $scope.startDate = {
      startDate: 0
    };
    $scope.endDate = {
      startDate: 0
    };
    $scope.setDateRange = function(year) {
      $scope.currentYear = year;
      return $timeout(function() {
        $scope.startDate.startDate = new Date(year, 0, 1).valueOf();
        $scope.endDate.startDate = new Date(year + 1, 0, 1).valueOf();
        updateMonths();
        updateTargets();
        return updateProperties();
      });
    };
    $scope.setDateRange($scope.years[0]);
function getUtcMonthKey(date) {
  var d = new Date(date);
  return d.getUTCFullYear() + '-' + d.getUTCMonth();
}

function updateTargets() {
  if (
    !$scope ||
    !$scope.targets ||
    !$scope.targets.items ||
    !$scope.targets.items.length ||
    !$scope.months ||
    !$scope.months.length
  ) {
    return;
  }

  var items = $scope.targets.items;
  var months = $scope.months;

  for (var i = 0; i < items.length; i++) {
    var target = items[i];
    var targetKey = getUtcMonthKey(target.date);
    for (var j = 0; j < months.length; j++) {
      var month = months[j];
      if (
        month.date &&
        getUtcMonthKey(month.date) === targetKey
      ) {
        month.target = target;
        break;
      }
    }
  }
}

    updateProperties = async function() {
      var res;
      res = (await $http.post($http.sites["lettings"].url + "/api/agreed/search", {
        startDate: $scope.startDate.startDate,
        endDate: $scope.endDate.startDate
      }, $http.sites["lettings"].config));
      return $timeout(function() {
        $scope.months = res.data;
        $scope.months.forEach(function(month) {
          return month.month = $filter('date')(month.date, 'MMMM');
        });
        updateTargets();
        $scope.firstLoad = true;
      });
    };
    $scope.targets = $scope.list('lettings:targets', {
      where: {
        type: 'letAgreed'
      }
    }, () => {
      $timeout(updateTargets);
    });
    $scope.properties = $scope.list('lettings:properties', {
      sort: 'proposedMoving',
      sortDir: 'ASC',
      pageSize: 1
    }, function() {
      return updateProperties();
    });
    $scope.open = function(selectedMonth) {
      var i, len, month, open, ref;
      open = selectedMonth.open;
      ref = $scope.months;
      for (i = 0, len = ref.length; i < len; i++) {
        month = ref[i];
        month.open = false;
      }
      return selectedMonth.open = !open;
    };
    $scope.edit = function(property) {
      if (!property.$override) {
        property.$override = {
          address: property.address,
          commission: property.commission,
          date: property.date
        };
      }
      return $timeout(function() {
        return property.$editing = true;
      });
    };
    $scope.delete = function(property) {
      return $http.post($http.sites["lettings"].url + `/api/properties/${property._id}`, {
        override: {
          deleted: true
        }
      }, $http.sites.lettings.config);
    };
    $scope.save = function(property) {
      return $http.post($http.sites["lettings"].url + `/api/properties/${property._id}`, {
        override: property.$override
      }, $http.sites.lettings.config);
    };
    $scope.cancel = function(property) {
      return property.$editing = false;
    };
    return $scope.saveTarget = function(month) {
      month.target._id = month.target._id || Math.floor(Math.random() * 9999999999999999).toString(26);
      $http.post($http.sites["lettings"].url + `/api/targets/${month.target._id || ''}`, month.target, $http.sites.lettings.config);
      return month.editing = false;
    };
  });

}).call(this);
