// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsContractorsCtrl', function($scope, Sorter, alert) {
    $scope.page = 1;
    $scope.limit = 15;
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.contractors = $scope.list('maintenance_leads:contractors', {
      page: 1,
      pageSize: $scope.limit,
      sort: 'name',
      sortDir: 'ASC'
    }, function(contractors) {
      var contractor, i, len, ref, results;
      ref = contractors.items;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        contractor = ref[i];
        results.push(contractor.issues = $scope.list('maintenance_leads:issues', {
          where: {
            statusName: 'Booked',
            $or: [
              {
                booked: contractor._id
              },
              {
                contractorName: contractor.name
              }
            ]
          }
        }));
      }
      return results;
    });
    $scope.contractors.sort = Sorter.create($scope.contractors.args);
    return $scope.deleteContractor = function(contractor) {
      return $scope.modal({
        template: require('../../modals/contractor-delete/contractor-delete.html').default,
        controller: 'maintenance_leadsIssueDeleteCtrl',
        size: 'small'
      }, $http.sites["maintenance_leads"].config).then(function() {
        $scope.contractors.delete(contractor);
        $state.go('contractors');
        return alert.log('Contractor deleted');
      }, function(err) {
        return console.log('err', err);
      });
    };
  });

}).call(this);
