// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings').config(function($stateProvider) {
    $stateProvider.state('lettings_forgot', {
      url: '/lettings/forgot',
      template: require("./forgot.html").default,
      controller: 'lettingsForgotCtrl'
    });
    return $stateProvider.state('lettings_forgotResponse', {
      url: '/lettings/forgot/:token',
      templateUrl: 'routes/forgot/forgot.html',
      controller: 'lettingsForgotCtrl'
    });
  });

}).call(this);
