// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').controller('leadsLeadsCtrl', function($scope, $stateParams, Sorter) {
    $scope.leads = $scope.list('leads:leads', {
      where: JSON.parse(JSON.stringify($stateParams)),
      sort: 'date',
      sortDir: 'DESC',
      page: 1,
      pageSize: 20
    });
    $scope.allleads = $scope.list('leads:leads', {
      where: JSON.parse(JSON.stringify($stateParams)),
      page: 1,
      pageSize: 0
    });
    $scope.sort = Sorter.create($scope.leads.args);
    return $scope.roleType = $stateParams.roleType;
  });

}).call(this);
