// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsProfileCtrl', function($scope, Auth) {
    return $scope.profile = $scope.single('lettings:users', Auth.getUser()._id);
  });

}).call(this);
