// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencySolicitorsCtrl', function($scope, env) {
    var getSolicitor, pushProperty, reduce;
    $scope.solicitors = [];
    reduce = function(name) {
      return (name || 'Unknown').toLowerCase().replace(/solicitor(s*)/g, '').replace(/law|llp/g, '').replace(/ll/g, 'l').replace(/ [a-z] /, '').replace(' & ', '').replace(' and ', '').replace(/\s+/g, '');
    };
    getSolicitor = function(name) {
      var i, len, ref, solicitor;
      ref = $scope.solicitors;
      for (i = 0, len = ref.length; i < len; i++) {
        solicitor = ref[i];
        if (reduce(solicitor.name) === reduce(name)) {
          return solicitor;
        }
      }
      solicitor = {
        id: $scope.solicitors.length,
        name: name || 'Unknown',
        properties: []
      };
      $scope.solicitors.push(solicitor);
      return solicitor;
    };
    pushProperty = function(solicitor, property, role) {
      var i, len, prop, ref;
      ref = solicitor.properties;
      for (i = 0, len = ref.length; i < len; i++) {
        prop = ref[i];
        if (prop.RoleId === property.RoleId) {
          prop[role] = solicitor.id;
          return prop;
        }
      }
      property[role] = solicitor.id;
      solicitor.properties.push(property);
      return property;
    };
    $scope.propsOpts = {
      where: {
        RoleStatus: 'OfferAccepted',
        RoleType: 'Selling',
        IncludeStc: true
      },
      transform: {
        items: 'Collection',
        total: 'TotalCount'
      }
    };
    $scope.properties = $scope.list({
      route: `${env.PROPERTY_URL}/search`
    }, $scope.propsOpts, function(properties) {
      var i, len, property, ref, results;
      ref = properties.items;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        property = ref[i];
        property.displayAddress = `${property.Address.Number} ${property.Address.Street}, ${property.Address.Locality}, ${property.Address.Town}, ${property.Address.Postcode}`;
        property.$case = $scope.single('agency:properties', property.RoleId, function(item) {
          var override, ref1, ref2, solicitor;
          item.locked = true;
          if (item.item) {
            item.item.override = item.item.override || {};
            override = item.item.override;
            if (!override.deleted) {
              item.$parent.address = override.address || item.$parent.displayAddress;
              item.$parent.commission = override.commission || item.item.role.Commission;
              item.$parent.date = new Date(override.date || item.item.startDate || item.item.progressions[0].milestones[0][0].startTime).valueOf();
              solicitor = getSolicitor((ref1 = item.item.purchasersSolicitor) != null ? ref1.role : void 0);
              pushProperty(solicitor, item.$parent, 'purchaser');
              solicitor = getSolicitor((ref2 = item.item.vendorsSolicitor) != null ? ref2.role : void 0);
              return pushProperty(solicitor, item.$parent, 'vendor');
            }
          }
        });
        results.push(property.$case.$parent = property);
      }
      return results;
    });
    return $scope.open = function(selectedSolicitor) {
      var i, len, open, ref, solicitor;
      open = selectedSolicitor.open;
      ref = $scope.solicitors;
      for (i = 0, len = ref.length; i < len; i++) {
        solicitor = ref[i];
        solicitor.open = false;
      }
      return selectedSolicitor.open = !open;
    };
  });

}).call(this);
