// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').config(function($stateProvider) {
    return $stateProvider.state('maintenance_forgot', {
      url: '/maintenance/forgot',
      template: require("./forgot.html").default,
      controller: 'maintenanceForgotCtrl'
    });
  });

}).call(this);
