// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').controller('maintenanceForgotCtrl', function($scope, $http, $state) {
    $scope.token = window.location.search.replace(/^\?/, '');
    $scope.submitEmail = function() {
      if ($scope.emailForm.$valid) {
        return $http.post('/get-forgot-code', {
          email: $scope.email
        }, $http.sites["maintenance"].config).then(function(response) {
          return true;
        });
      }
    };
    return $scope.submitPass = function() {
      if ($scope.repeatPassword === $scope.password) {
        return $http.post(`/forgot-update/${$scope.token}`, {
          password: $scope.password
        }, $http.sites["maintenance"].config).then(function(response) {
          if (response.data === 'OK') {
            return $state.go('dashboard');
          }
        }, function(err) {
          return false;
        });
      } else {
        return $scope.error = 'Passwords must match';
      }
    };
  });

}).call(this);
