// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var e;

  angular.module('vs-leads', ['ndx', 'ui.router', 'ng-sumoselect', 'ui.gravatar', 'multi-check']).config(function($locationProvider, $urlRouterProvider, gravatarServiceProvider, $httpProvider, AuthProvider) {
    $urlRouterProvider.otherwise('/');
    $locationProvider.html5Mode(true);
    return gravatarServiceProvider.defaults = {
      size: 16,
      "default": 'mm',
      rating: 'pg'
    };
  }).run(function($http, env, $rootScope, $state) {
    $http.defaults.headers.common.Authorization = `Bearer ${env.PROPERTY_TOKEN}`;
    return $rootScope.state = function(route) {
      if ($state && $state.current) {
        if (Object.prototype.toString.call(route) === '[object Array]') {
          return route.indexOf($state.current.name) !== -1;
        } else {
          return route === $state.current.name;
        }
      }
      return false;
    };
  });

  try {
    angular.module('ndx');
  } catch (error) {
    e = error;
    angular.module('ndx', []); //ndx module stub
  }

}).call(this);
