// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsIssuesCtrl', function($scope, Sorter) {
    $scope.page = 1;
    $scope.limit = 15;
    $scope.mysearch = {
      $like: ''
    };
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.issues = $scope.list('maintenance_leads:issues', {
      page: 1,
      pageSize: $scope.limit,
      sort: 'date',
      sortDir: 'DESC',
      where: {
        statusName: 'Reported',
        search: $scope.mysearch
      }
    });
    return $scope.sort = Sorter.create($scope.issues.args);
  });

}).call(this);
