// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-agency').filter('getFeedbackCount', function() {
    return function(property) {
      var count, i, len, ref, viewing;
      if (!property) {
        return;
      }
      count = 0;
      ref = property.viewings;
      for (i = 0, len = ref.length; i < len; i++) {
        viewing = ref[i];
        count += (viewing.Feedback || []).length;
      }
      return count;
    };
  });

}).call(this);
