// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings').config(function($stateProvider) {
    return $stateProvider.state('lettings_invited', {
      url: '/lettings/invite/:code',
      template: require("./invited.html").default,
      controller: 'lettingsInvitedCtrl'
    });
  });

}).call(this);
