// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsCreateWorksOrderCtrl', function($scope, $stateParams, $http, alert) {
    $scope.worksOrder = {};
    $scope.issue = $scope.single('maintenance_leads:issues', $stateParams, function(issue) {
      console.log('issue', issue);
    });
    $scope.contractors = $scope.list('maintenance_leads:contractors', null, (contractors) => {
      contractors.items.sort((a, b) => a.name > b.name ? 1 : -1);
    });
    $scope.landlords = $scope.list('maintenance_leads:landlords');
    $scope.submit = () => {
      console.log('worksOrder', $http.sites);
      $scope.submitted = true;
      if(!$scope.worksOrderForm.$valid) {
        return;
      }
      const contractor = $scope.contractors.items.find(contractor => contractor._id === $scope.worksOrder.contractor);
      const htmldiv = document.createElement('div');
      const newIssue = !$scope.issue.item._id;
      htmldiv.innerHTML = `
        <style>
          p, h1 {margin:0!important}
          h3 {margin:5px 0 0 0!important}
          h2 {margin:10px 0 0 0!important}
          .worksorder-body {
            height: 950px;
            min-height: 950px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
          }
          img {
            max-width: 100%;
          }
          p {
            font-size: 1.4rem!important;
          }
          h1 {
            font-size: 1.8rem!important;
          }
          h2 {
            font-size: 1.6rem!important;
          }
          h3 {
            font-size: 1.4rem!important;
          }
        </style>
        <div class="worksorder-body">
          <div class="worksorder-main">
            <center><img src="/public/img/worksorder-header.jpeg" /></center>
            <h3><strong>${contractor.name}</strong></h3>
            <p>${contractor.phone}</p>
            <p>${contractor.email}</p>
            <h2>VITALSPACE</h2>
            <h1 class="orange">WORKSHEET</h1>
            <h3><strong>Date</strong></h3>
            <p>${new Date($scope.worksOrder.date).toDateString()}</p>
            <h3><strong>Priority</strong></h3>
            <p>${$scope.worksOrder.priority || ''}</p>
            <h2 class="orange">Property Address</h2>
            <p>${(newIssue ? $scope.worksOrder.address : $scope.issue.item.address) || ''}</p>
            <h2 class="orange">Tenant Details</h2>
            <p>${(newIssue ? $scope.worksOrder.tenant : $scope.issue.item.tenant) || ''}</p>
            <p>${(newIssue ? $scope.worksOrder.tenantPhone : $scope.issue.item.tenantPhone) || ''}</p>
            <p>${(newIssue ? $scope.worksOrder.tenantEmail : $scope.issue.item.tenantEmail) || ''}</p>
            <h2 class="orange">Issue Details</h2>
            <h3><strong>Issue Title</strong></h3>
            <p>${ (newIssue ? $scope.worksOrder.issueTitle : $scope.issue.item.title) || '' }</p>
            <h3><strong>Fault Detail</strong></h3>
            <p>${ (newIssue ? $scope.worksOrder.issueDetails : $scope.issue.item.details) || '' }</p>
      `;
      if($scope.worksOrder.notes) {
        htmldiv.innerHTML += `
          <h3><strong>Additional Notes</strong></h3>
          <p>${ $scope.worksOrder.notes }</p>
        `
      }
      htmldiv.innerHTML += `
          </div>
          <div class="worksorder-footer">
            <center><img src="/public/img/worksorder-footer.jpeg" /></center>
          </div>
        </div>
      `
      const htmlContent = htmldiv;
      const pdfOptions = {
        margin: 10,
        filename: 'generated.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 1 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      };
      console.log('pdf start');
      html2pdf()
        .from(htmlContent)
        .set(pdfOptions)
        .outputPdf()
        .toPdf()
        .get('pdf')
        .then(pdf => {
          const pdfBlob = pdf.output('blob');

          const reader = new FileReader();
          reader.onload = function () {
            const pdfBase64 = reader.result.split(',')[1];
            const pdfFileName = `${parseInt(new Date().getTime().toString() + (Math.random() * 9999)).toString(20)}.pdf`;
            const pdfData = {
              base64: pdfBase64,
              filename: pdfFileName,
            };
            $http.post($http.sites["main"].url + '/api/upload-pdf', pdfData, $http.sites["main"].config)
              .then(response => {
                $scope.worksOrderForm.$setPristine();
                if (response.status===200) {
                  alert.log('PDF uploaded successfully');
                  if($scope.issue.item._id) {
                    $scope.issue.item.notes = $scope.issue.item.notes || [];
                    $scope.issue.item.notes.push({
                      date: new Date().getTime(),
                      item: 'Note',
                      side: '',
                      text: `## **Works order created**  \n<https://vitalspace-worksorders.s3.eu-west-1.amazonaws.com/${pdfFileName}>`,
                      user: $scope.auth.getUser()
                    })
                    $scope.issue.save();
                  }
                  else {
                    const link = document.createElement('a');
                    link.href = `https://vitalspace-worksorders.s3.eu-west-1.amazonaws.com/${pdfFileName}`;
                    link.target = '_blank';
                    link.click();
                  }
                  $scope.worksOrder = {};
                  $scope.cancel();
                } else {
                  alert.log('Error uploading PDF');
                }
              })
              .catch(error => {
                alert.log('Error uploading PDF:', error);
              });
          }
          reader.readAsDataURL(pdfBlob);
        });
    }
  });

}).call(this);
