// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsAddWorksOrderModalCtrl', function($scope, $http, ndxModalInstance, data, env) {
    $scope.data = data || {};
    $scope.submitted = false;
    
    // Initialize works order object
    if ($scope.data.worksOrder) {
      $scope.worksOrder = $scope.data.worksOrder;
    } else {
      $scope.worksOrder = {
        date: new Date(),
        priority: 'Low',
        moveOutWorks: 'Tenancy Issue'
      };
      
      // If coming from an issue, pre-populate data
      if ($scope.data.issue) {
        $scope.worksOrder.issueId = $scope.data.issue._id;
        $scope.worksOrder.address = $scope.data.issue.address1 + ', ' + ($scope.data.issue.address2 ? $scope.data.issue.address2 + ', ' : '') + $scope.data.issue.postcode;
        $scope.worksOrder.tenant = $scope.data.issue.tenantFirstName + ' ' + $scope.data.issue.tenantLastName;
        $scope.worksOrder.tenantPhone = $scope.data.issue.tenantPhone;
        $scope.worksOrder.tenantEmail = $scope.data.issue.tenantEmail;
        $scope.worksOrder.issueTitle = $scope.data.issue.title;
        $scope.worksOrder.issueDetails = $scope.data.issue.details;
      }
    }
    
    // Load contractors
    $scope.contractors = $scope.list('maintenance_leads:contractors', {
      page: 1,
      pageSize: 1000,
      sort: 'name',
      sortDir: 'ASC'
    });
    
    $scope.submit = function() {
      $scope.submitted = true;
      
      if ($scope.worksOrderForm.$valid) {
        $http.post(env.API_URL + '/maintenance_leads/works-orders', $scope.worksOrder).then(function(response) {
          ndxModalInstance.close(response.data);
        }, function(err) {
          console.error('Error creating works order:', err);
          alert('Error creating works order. Please try again.');
        });
      }
    };
    
    $scope.cancel = function() {
      ndxModalInstance.dismiss();
    };
  });

}).call(this);
