// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsWorksOrdersCtrl', function($scope, Sorter, DbItem) {
    console.log('works orders');
    $scope.dbItem = DbItem;
    $scope.page = 1;
    $scope.limit = 15;
    $scope.mysearch = {
      $like: ''
    };
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.issues = $scope.list('maintenance_leads:issues', {
      page: 1,
      pageSize: 10,
      sort: 'date',
      sortDir: 'DESC',
      where: {
        statusName: 'Booked',
        search: $scope.mysearch,
        status: {
          booked: true,
          completed: false,
          invoiced: false
        }
      }
    });
    return $scope.sort = Sorter.create($scope.issues.args);
  });

}).call(this);
