// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').config(function($stateProvider) {
    return $stateProvider.state('lettings_marketing_item', {
      url: '/lettings/marketing/:id',
      template: require("./marketing-item.html").default,
      controller: 'lettingsMarketingItemCtrl',
      data: {
        title: 'Vitalspace Lettings - Marketing Details',
		auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
