// Generated by CoffeeScript 2.5.1
(function() {
    'use strict';
    angular.module('vs-lettings-inner').controller('lettingsMarketingItemCtrl', function($scope, $stateParams, env, $http) {
        $scope.marketing = $scope.single('lettings:marketing', $stateParams.id);
    });

}).call(this);
