// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').config(function($stateProvider) {
    return $stateProvider.state('maintenance_profile', {
      url: '/maintenance/profile',
      template: require("./profile.html").default,
      controller: 'maintenanceProfileCtrl',
	  data: {
        title: 'Vitalspace Maintenance - Profile',
		auth: ['maintenance:agency', 'maintenance:maintenance', 'maintenance:admin', 'maintenance:superadmin']
	  },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['maintenance:agency', 'maintenance:maintenance', 'maintenance:admin', 'maintenance:superadmin']);
        }
      }
    });
  });

}).call(this);
