// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').controller('maintenanceProfileCtrl', function($scope, Auth) {
    return $scope.profile = $scope.single('maintenance:users', Auth.getUser()._id);
  });

}).call(this);
